SELECT
        TABLES.TABLE_SCHEMA + '.' + TABLES.TABLE_NAME,
        COLUMNS.COLUMN_NAME,
        COLUMNS.DATA_TYPE,
        COLUMNS.CHARACTER_MAXIMUM_LENGTH
    FROM 
        INFORMATION_SCHEMA.COLUMNS,
        INFORMATION_SCHEMA.TABLES
    WHERE
        COLUMNS.TABLE_NAME = TABLES.TABLE_NAME
        AND TABLES.TABLE_SCHEMA = 'dbo'
    ORDER BY
        TABLES.TABLE_SCHEMA,
        TABLES.TABLE_NAME,
        COLUMNS.COLUMN_NAME